name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test-cmake:
    name: ${{ matrix.os }} / Python ${{ matrix.python-version }} / CMake${{ matrix.bounds_check && ' + BOUNDS_CHECK' || '' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13', '3.14' ]
        build_type: [ Release ]
        bounds_check: [ false, true ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pybind11 numpy pytest

      - name: Configure (CMake)
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_TESTING=ON ${{ matrix.bounds_check && '-DCNDA_BOUNDS_CHECK=ON' || '' }}

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} -j

      - name: Test (CTest - C++ tests)
        run: ctest --test-dir build --output-on-failure --build-config ${{ matrix.build_type }}

      - name: Build and install Python package
        run: python -m pip install -e .

      - name: Test (pytest - Python tests)
        run: python -m pytest tests/python/ -v